language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t crazia -f Dockerfile.dev .

script:
  - docker run -e CI=true crazia npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Docke"
  env: "Docke-env"
  bucket_name: "elasticbeanstalk-us-east-2-624759150761"
  bucket_path: "Docke"
     on:
        branch: master
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key: $AWS_SECRET_KEY
   