FROM node:lts-alpine3.9 as builder
WORKDIR '/app'
COPY package.json .
RUN npm install
COPY . .
RUN npm run build
#questo termina il blocco precedente
FROM nginx 
COPY --from=builder /app/build /usr/share/nginx/html
